language: rust
matrix:
  include:
    - os: osx
      rust: beta
    - rust: beta
    - rust: nightly
      script:
        - cargo test
        - cargo bench
        - cd compiletest
        - cargo clean
        - cargo test
        - cd ../

    - rust: nightly
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      script:
        - cargo doc --no-deps --all-features
      after_success:
        - travis-cargo --only nightly doc-upload
script:
  - cargo test
